"""AnalyzeExecutor — post-processing and analysis of simulation results.

Two modes of operation:

1. Default mode (triggered by ReviewResult with route="analyze"):
   Runs standard post-processing automatically after simulation:
   - PartVTK: export fluid particles as VTK for ParaView
   - MeasureTool: extract probe data
   - Opens ParaView with the results

2. Analysis mode (triggered by AnalysisRequest):
   LLM-driven: takes the user's natural language analysis request,
   reasons about which post-processing tools and Python analysis to run,
   executes them, and returns results.
"""

import json
import logging
import os

from openai import AsyncOpenAI

from agent_framework import (
    Executor,
    MCPStdioTool,
    WorkflowContext,
    handler,
)

from agents.schemas import AnalysisRequest, AnalysisResult, ReviewResult
from agents.utils.skill_loader import get_postprocess_skill_content
from agents.tools.visualize_geometry import visualize_geometry

logger = logging.getLogger(__name__)

_ANALYSIS_SYSTEM_PROMPT = """\
You are an expert DualSPHysics post-processing engineer. You will be given:
1. The simulation context (run directory layout, plan parameters, probe points).
2. The user's analysis request.
3. Reference material for available post-processing tools.

Your job is to figure out what post-processing steps are needed and return
a JSON object with a "steps" array. Each step is one of:

1. A post-processing tool call:
   {"type": "postprocess", "tool_name": "<name>", "args": ["arg1", "arg2", ...]}

2. A Python analysis script:
   {"type": "python", "code": "<python_code>", "description": "<what it does>"}

IMPORTANT — all paths are RELATIVE to the run directory:
  out/data/           — raw simulation .bi4 files
  out/particles/      — VTK exports (already generated by default post-processing)
  out/measuretool/    — MeasureTool CSV outputs (already generated if probes exist)
  out/analysis/       — put new output files here

Guidelines:
- ALL paths in postprocess args must be relative (e.g. "out/data", "out/analysis/Fluid").
  The tool runs with the run directory as cwd.
- If existing files are available (listed in context), prefer using Python to parse
  them directly rather than re-running the post-processing tool.
- Use run_postprocess for PartVTK, IsoSurface, ComputeForces, etc.
- Use Python for parsing CSVs, computing derived quantities, and plotting.
- In Python code, use matplotlib with Agg backend for plots.
- Python code runs with out/analysis/ as cwd. Use relative paths for output files.
  To access other directories, use ../data/, ../particles/, ../measuretool/.
- PartVTK CSV uses semicolon separator by default. Use numpy.genfromtxt with delimiter=";".
- PartVTK CSV columns: Idp;Pos.x;Pos.y;Pos.z;Vel.x;Vel.y;Vel.z;Rhop (when vars include idp,vel,rhop).
- Always add -csvsep:0 for semicolon CSVs (default) or -csvsep:1 for comma.
- In Python, to get TimeOut value for time axis, it's provided in the context.

Return valid JSON only, no markdown fences. Example:
{"steps": [
  {"type": "postprocess", "tool_name": "partvtk", "args": ["-dirin", "out/data", "-savecsv", "out/analysis/PartFluid", "-onlytype:-all,+fluid", "-vars:+idp,+vel,+rhop"]},
  {"type": "python", "code": "import glob\\nimport numpy as np\\n...", "description": "Compute max run-out distance over time"}
]}
"""


async def _plan_analysis(context: str, request: str) -> dict:
    """Ask LLM to plan analysis steps."""
    skill_text = get_postprocess_skill_content()

    user_content = (
        f"### Simulation Context\n{context}\n\n"
        f"### Reference Material\n{skill_text}\n\n"
        f"### User Request\n{request}"
    )

    client = AsyncOpenAI()
    response = await client.chat.completions.create(
        model=os.getenv("ANALYSIS_MODEL", "gpt-4o"),
        temperature=0,
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": _ANALYSIS_SYSTEM_PROMPT},
            {"role": "user", "content": user_content},
        ],
    )

    raw = response.choices[0].message.content or '{"steps": []}'
    return json.loads(raw)


class AnalyzeExecutor(Executor):
    """Post-processing and analysis of simulation results."""

    def __init__(self, mcp: MCPStdioTool, base_dir: str) -> None:
        super().__init__(id="analyze")
        self.mcp = mcp
        self.base_dir = base_dir

    @handler
    async def on_sim_complete(
        self, trigger: ReviewResult, ctx: WorkflowContext[AnalysisResult]
    ) -> None:
        """Default post-processing after simulation completes."""
        run_dir = ctx.get_state("run_dir")
        assert run_dir is not None, "No run_dir in workflow state"

        # All paths relative to run_dir; tools run with cwd=run_dir
        particles_dir = f"{run_dir}/out/particles"

        try:
            # 1. PartVTK: export fluid particles as VTK
            logger.info(">>> partvtk (fluid VTK)")
            r = await self.mcp.call_tool(
                "run_postprocess",
                postprocess_tool="partvtk",
                cwd=run_dir,
                args=[
                    "-dirin", "out/data",
                    "-savevtk", "out/particles/PartFluid",
                    "-onlytype:-all,+fluid",
                    "-vars:+idp,+vel,+rhop,+press",
                ],
            )
            partvtk_result = json.loads(r) if isinstance(r, str) else r
            if partvtk_result.get("returncode", -1) != 0:
                logger.warning("PartVTK failed: %s", partvtk_result.get("stderr"))

            # 2. PartVTK: export boundary particles as VTK
            logger.info(">>> partvtk (boundary VTK)")
            r = await self.mcp.call_tool(
                "run_postprocess",
                postprocess_tool="partvtk",
                cwd=run_dir,
                args=[
                    "-dirin", "out/data",
                    "-savevtk", "out/particles/PartBound",
                    "-onlytype:-all,+bound",
                    "-vars:+mk,+rhop",
                ],
            )

            # 3. MeasureTool: probe data (if points file exists)
            points_file = f"{run_dir}/PointsMeasure_Points.txt"
            csv_files = []
            if os.path.exists(points_file):
                logger.info(">>> run_measuretool")
                r = await self.mcp.call_tool(
                    "run_measuretool",
                    data_dir=f"{run_dir}/out/data",
                    points_file=points_file,
                    output_csv_stem=f"{run_dir}/out/measuretool/PointsMeasure",
                )
                mt_result = json.loads(r) if isinstance(r, str) else r
                csv_files = mt_result.get("csv_files", [])

            # 4. Compute metrics (if ground truth exists)
            gt_csv = f"{self.base_dir}/cases/ground_truth/PointsMeasure.csv"
            metrics = {}
            if csv_files and os.path.exists(gt_csv):
                logger.info(">>> compute_metrics")
                r = await self.mcp.call_tool(
                    "compute_metrics",
                    result_csv=csv_files[0],
                    ground_truth_csv=gt_csv,
                )
                metrics = json.loads(r) if isinstance(r, str) else r

            # 5. Open ParaView with fluid VTK
            logger.info(">>> visualize results")
            viz_result = visualize_geometry(particles_dir)
            logger.info("visualize: %s", viz_result)

            # Collect all output files
            output_files = partvtk_result.get("output_files", []) + csv_files

            summary_parts = [
                "Default post-processing complete:",
                f"  - Fluid VTK files: out/particles/PartFluid_*.vtk",
                f"  - Boundary VTK files: out/particles/PartBound_*.vtk",
            ]
            if csv_files:
                # Show relative paths in summary
                rel_csvs = [os.path.relpath(f, run_dir) for f in csv_files]
                summary_parts.append(f"  - Probe CSVs: {', '.join(rel_csvs)}")
            if metrics.get("rmse") is not None:
                summary_parts.append(
                    f"  - Metrics: RMSE={metrics['rmse']:.6f}, "
                    f"correlation={metrics.get('correlation', 'N/A')}"
                )

            await ctx.send_message(AnalysisResult(
                run_dir=run_dir,
                success=True,
                message="\n".join(summary_parts),
                output_files=output_files,
            ))

        except Exception as exc:
            logger.exception("Default post-processing failed")
            await ctx.send_message(AnalysisResult(
                run_dir=run_dir,
                success=False,
                message=str(exc),
                output_files=[],
            ))

    @handler
    async def on_analysis_request(
        self, req: AnalysisRequest, ctx: WorkflowContext[AnalysisResult]
    ) -> None:
        """LLM-driven analysis based on user request."""
        run_dir = ctx.get_state("run_dir")
        plan_data = ctx.get_state("plan")
        assert run_dir is not None, "No run_dir in workflow state"

        # Build context for the LLM — all paths relative to run_dir
        context_parts = [
            "All paths below are relative to the run directory.",
            "  out/data/          — raw simulation .bi4 files",
            "  out/particles/     — VTK exports",
            "  out/measuretool/   — MeasureTool CSV outputs",
            "  out/analysis/      — analysis output (put new files here)",
        ]
        if plan_data:
            params = plan_data.get("params", {})
            context_parts.append(f"TimeOut (output interval): {params.get('TimeOut', 0.1)} s")
            context_parts.append(f"TimeMax: {params.get('TimeMax', 5.0)} s")
            context_parts.append(f"Probe points: {plan_data.get('probe_points', [])}")
            context_parts.append(f"Physics params: {json.dumps(params, indent=2)}")

        # List existing output files so LLM can use them directly
        existing_files = []
        for subdir in ["out/particles", "out/measuretool", "out/analysis"]:
            full_dir = os.path.join(run_dir, subdir)
            if os.path.isdir(full_dir):
                for f in sorted(os.listdir(full_dir)):
                    existing_files.append(os.path.join(subdir, f))
        if existing_files:
            context_parts.append("\nExisting output files:\n" + "\n".join(f"  - {f}" for f in existing_files[:50]))

        context = "\n".join(context_parts)

        try:
            # Ask LLM to plan the analysis
            plan = await _plan_analysis(context, req.feedback)
            steps = plan.get("steps", [])

            if not steps:
                await ctx.send_message(AnalysisResult(
                    run_dir=run_dir,
                    success=False,
                    message="LLM returned no analysis steps.",
                    output_files=[],
                ))
                return

            all_output_files = []
            summaries = []

            # Create analysis output directory
            analysis_dir = f"{run_dir}/out/analysis"
            os.makedirs(analysis_dir, exist_ok=True)

            for i, step in enumerate(steps):
                step_type = step.get("type")

                if step_type == "postprocess":
                    tool_name = step["tool_name"]
                    args = step["args"]
                    logger.info(">>> analysis step %d: %s %s", i, tool_name, args)

                    r = await self.mcp.call_tool(
                        "run_postprocess",
                        postprocess_tool=tool_name,
                        args=args,
                        cwd=run_dir,
                    )
                    result = json.loads(r) if isinstance(r, str) else r
                    if result.get("returncode", -1) != 0:
                        err_msg = result.get("stderr") or result.get("stdout") or "unknown error"
                        logger.warning("Step %d failed (rc=%s): %s", i, result.get("returncode"), err_msg[:500])
                        summaries.append(f"Step {i+1} ({tool_name}): FAILED - {err_msg[:300]}")
                    else:
                        files = result.get("output_files", [])
                        all_output_files.extend(files)
                        summaries.append(f"Step {i+1} ({tool_name}): OK - {len(files)} files")

                elif step_type == "python":
                    desc = step.get("description", "Python analysis")
                    code = step["code"]
                    logger.info(">>> analysis step %d: python - %s", i, desc)

                    r = await self.mcp.call_tool(
                        "run_analysis",
                        python_code=code,
                        work_dir=analysis_dir,
                    )
                    result = json.loads(r) if isinstance(r, str) else r
                    if result.get("returncode", -1) != 0:
                        err_msg = result.get("stderr") or result.get("stdout") or "unknown error"
                        logger.warning("Step %d failed (rc=%s): %s", i, result.get("returncode"), err_msg[:500])
                        summaries.append(f"Step {i+1} ({desc}): FAILED - {err_msg[:300]}")
                    else:
                        stdout = result.get("stdout", "").strip()
                        files = result.get("output_files", [])
                        all_output_files.extend(files)
                        summary = f"Step {i+1} ({desc}): OK"
                        if files:
                            summary += f" - generated {', '.join(os.path.basename(f) for f in files)}"
                        if stdout:
                            summary += f"\n    Output: {stdout}"
                        summaries.append(summary)
                else:
                    summaries.append(f"Step {i+1}: unknown type '{step_type}'")

            await ctx.send_message(AnalysisResult(
                run_dir=run_dir,
                success=True,
                message="Analysis complete:\n" + "\n".join(summaries),
                output_files=all_output_files,
            ))

        except Exception as exc:
            logger.exception("Analysis failed")
            await ctx.send_message(AnalysisResult(
                run_dir=run_dir,
                success=False,
                message=str(exc),
                output_files=[],
            ))
